import "./css/style.css";

import {
  Inter,
  Architects_Daughter,
} from "next/font/google";

import { cn } from "@/lib/utils";

import Header from "@/components/ui/header";
import Banner from "@/components/banner";
import ContextProvider from "@/contexts/ContextProvider";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const architects_daughter = Architects_Daughter({
  subsets: ["latin"],
  variable: "--font-architects-daughter",
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased bg-gray-900 text-gray-200 tracking-tight",
          fontSans.variable,
          architects_daughter.variable
        )}
      >
        <div className="flex flex-col min-h-screen overflow-hidden">
          <ContextProvider>
            {children}
          </ContextProvider>
        </div>
      </body>
    </html>
  );
}